theme: jekyll-theme-minimal
title: leland's homepage
description: building new website
domain: lelandling.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://lelandling.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /docs/      # place folder name if the site is served in a subfolder


show_related_posts: True
show_post_footers: True
show_subscribe_cta: True
show_social_icons: True
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: true

# Social icons
github_username: thundergolfer
stackoverflow_id:
twitter_username: jonobelotti_io
linkedin_username: jonathonbelotti

text:
  pagination:
    newer: "Newer"
    older: "Older"
  post:
    updated: "Updated"
    minute_read: "minute read"
    related_posts: "More to read"
  index:
    coming_soon: "Coming soon..."
  og_locale: "en_US"

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "with_toc_data", "footnotes"]
permalink: pretty
paginate: 12
paginate_path: "/blog/:num/"
sass:
  compressed: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

collections_dir: collections
collections:
  reviews:
    output: true
  portfolio:
    output: true